### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [68]:
import numpy as np
import matplotlib.pyplot as plt

vector = np.random.rand(10)
display(vector.shape)
display(vector)

(10,)

array([0.96562612, 0.32683058, 0.05041227, 0.58791761, 0.99396877,
       0.47353856, 0.75704922, 0.25702611, 0.89357261, 0.56673402])

In [69]:
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

display(matrix)
display(matrix.shape)

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [70]:
vector_rounded = np.round((vector + 10), 2)
vector_rounded

array([10.97, 10.33, 10.05, 10.59, 10.99, 10.47, 10.76, 10.26, 10.89,
       10.57])

In [71]:
vector_mult = vector_rounded * 2
vector_mult

array([21.94, 20.66, 20.1 , 21.18, 21.98, 20.94, 21.52, 20.52, 21.78,
       21.14])

In [72]:
v = vector_mult**2
v

array([481.3636, 426.8356, 404.01  , 448.5924, 483.1204, 438.4836,
       463.1104, 421.0704, 474.3684, 446.8996])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [73]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [74]:
result_matrix = np.dot(A, B)
result_matrix

array([[0.232 , 0.1627, 0.2145],
       [0.3061, 0.4867, 0.633 ],
       [0.1393, 0.2261, 0.294 ]])

In [75]:
result2_matrix = np.dot(result_matrix, C)
result2_matrix

ValueError: shapes (3,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
result3_matrix = np.dot(result_matrix, D)
result3_matrix

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
result_matrix_transposed = result_matrix.T
result_matrix_transposed

array([[0.232 , 0.3061, 0.1393],
       [0.1627, 0.4867, 0.2261],
       [0.2145, 0.633 , 0.294 ]])

In [ ]:
vector_transposed = vector.T
display(vector_transposed.shape)
display(vector_transposed)

(10,)

array([0.72542276, 0.81136332, 0.41173337, 0.92663865, 0.27382794,
       0.26470163, 0.58858431, 0.08136084, 0.99492199, 0.71347426])

Ні, вектор залишився таким самим

In [ ]:
column_vector = np.expand_dims(a=vector, axis=1)
display(column_vector)
display(column_vector.shape)

array([[0.72542276],
       [0.81136332],
       [0.41173337],
       [0.92663865],
       [0.27382794],
       [0.26470163],
       [0.58858431],
       [0.08136084],
       [0.99492199],
       [0.71347426]])

(10, 1)

In [ ]:
column_vector_transposed = column_vector.T
display(column_vector_transposed)
display(column_vector_transposed.shape)

array([[0.72542276, 0.81136332, 0.41173337, 0.92663865, 0.27382794,
        0.26470163, 0.58858431, 0.08136084, 0.99492199, 0.71347426]])

(1, 10)

Після використання expand_dims вектор став матрицею з однією колонкою, або одним рядком після транспонування