### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [78]:
import numpy as np
import matplotlib.pyplot as plt

vector = np.random.rand(10)
display(vector.shape)
display(vector)

(10,)

array([0.8495847 , 0.45448134, 0.67719041, 0.98030321, 0.72821831,
       0.05545258, 0.7281987 , 0.71013037, 0.02893002, 0.06825353])

In [79]:
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

display(matrix)
display(matrix.shape)

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [80]:
vector_rounded = np.round((vector + 10), 2)
vector_rounded

array([10.85, 10.45, 10.68, 10.98, 10.73, 10.06, 10.73, 10.71, 10.03,
       10.07])

In [81]:
matrix_mult = matrix * 2
matrix_mult

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [82]:
v = vector ** 2
v

array([7.21794161e-01, 2.06553293e-01, 4.58586852e-01, 9.60994375e-01,
       5.30301903e-01, 3.07498901e-03, 5.30273349e-01, 5.04285149e-01,
       8.36945923e-04, 4.65854502e-03])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [73]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [83]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [84]:
result2_matrix = np.dot(result_matrix, C)
result2_matrix

array([[0.5202],
       [0.2846]])

In [85]:
result3_matrix = np.dot(result_matrix, D)
result3_matrix

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [86]:
result_matrix_transposed = result_matrix.T
result_matrix_transposed

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [87]:
vector_transposed = vector.T
display(vector_transposed.shape)
display(vector_transposed)

(10,)

array([0.8495847 , 0.45448134, 0.67719041, 0.98030321, 0.72821831,
       0.05545258, 0.7281987 , 0.71013037, 0.02893002, 0.06825353])

Ні, вектор залишився таким самим

In [88]:
column_vector = np.expand_dims(a=vector, axis=1)
display(column_vector)
display(column_vector.shape)

array([[0.8495847 ],
       [0.45448134],
       [0.67719041],
       [0.98030321],
       [0.72821831],
       [0.05545258],
       [0.7281987 ],
       [0.71013037],
       [0.02893002],
       [0.06825353]])

(10, 1)

In [89]:
column_vector_transposed = column_vector.T
display(column_vector_transposed)
display(column_vector_transposed.shape)

array([[0.8495847 , 0.45448134, 0.67719041, 0.98030321, 0.72821831,
        0.05545258, 0.7281987 , 0.71013037, 0.02893002, 0.06825353]])

(1, 10)

Після використання expand_dims вектор став матрицею з однією колонкою, або одним рядком після транспонування