**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [31]:
# Import library
import numpy as np

In [32]:
# Create arrays with different NumPy functions
arr = np.array([5, 15, 25, 35, 45])
arr1 = np.zeros(7, dtype=int)
arr2 = np.ones(6, dtype=int)
arr3 = np.arange(10,20)

# Display created arrays
display(arr)
display(arr1)
display(arr2)
display(arr3)

array([ 5, 15, 25, 35, 45])

array([0, 0, 0, 0, 0, 0, 0])

array([1, 1, 1, 1, 1, 1])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [33]:
# Create a NumPy array
base_values = np.array([12, 24, 36, 48, 60])

# Apply element operations
doubled_values = base_values * 2      # Multiply each element by 2
values_plus_ten = base_values + 10    # Add 10 to each element
squared_values = base_values ** 2     # Square each element
square_root_values = np.sqrt(base_values)  # Compute square root of each element

# Display the results
display(doubled_values)
display(values_plus_ten)
display(squared_values)
display(square_root_values)

array([ 24,  48,  72,  96, 120])

array([22, 34, 46, 58, 70])

array([ 144,  576, 1296, 2304, 3600])

array([3.46410162, 4.89897949, 6.        , 6.92820323, 7.74596669])


---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [34]:
# Create a NumPy array
data = np.array([18, 27, 33, 41, 52, 68, 79])

# Calculate summary statistics
mean_data = data.mean()
min_data = data.min()
max_data = data.max()
sum_data = data.sum()

# Display the results
display(mean_data)
display(min_data)
display(max_data)
display(sum_data)


45.42857142857143

18

79

318


---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [38]:
# Create a NumPy array
arr = np.array([15, 22, 35, 44, 58, 67])

# Access elements by position
first_element = arr[0]
last_element = arr[-1]

# Slice a subset of elements
elements = arr[1:4]

# Filter elements greater than 40
elements_more_40 = arr[arr > 40]

# Display the results
display(first_element)
display(last_element)
display(elements)
display(elements_more_40)

15

67

array([22, 35, 44])

array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [36]:
# Create an array
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [39]:
# Display the matrix dimensions (rows, columns)
display(matrix.shape)
# Display the first row of the matrix
display(matrix[0])
# Display the second column of the matrix
display(matrix[:,1])
# Display the sum of all matrix elements
display(matrix.sum())
# Display the mean of all matrix elements
display(matrix.mean())

(3, 3)

array([2, 4, 6])

array([ 4, 10, 16])

90

10.0